baseurl = "/"
metaDataFormat = "yaml"

languageCode = "ru"
languageLang = "ru"
defaultContentLanguage = "ru"

title = "Mercedes-37"

publishDir = "docs"
staticDir = "static"

relativeURLs = true
hrefTargetBlank = false

[params]
description = '''
'''
author = "Aventhor"
